// All placeholder data used while real backend data is not yet available.
// Replace section by section as each screen is wired to Supabase.

export const MOCK_VENUES = [
  {
    id: 'mock-1',
    name: 'Toybox',
    slug: 'toybox',
    neighbourhood: 'King West',
    neighbourhood_id: 'mock-kw',
    address: '554 King St W, Toronto',
    venue_type: 'nightclub' as const,
    vibe_tags: ['dancey', 'late-night', 'lgbtq'],
    music_genres: ['House', 'Electronic'],
    google_rating: 4.3,
    google_review_count: 820,
    has_cover_charge: true,
    cover_notes: 'Free before 11pm on weekdays',
    is_active: true,
    is_open_now: true,
    photo_url: null,
    lat: 43.6449,
    lng: -79.3981,
  },
  {
    id: 'mock-2',
    name: 'The Drake Hotel',
    slug: 'the-drake-hotel',
    neighbourhood: 'Ossington',
    neighbourhood_id: 'mock-os',
    address: '1150 Queen St W, Toronto',
    venue_type: 'bar' as const,
    vibe_tags: ['chill', 'live-music', 'first-date'],
    music_genres: ['Indie', 'Jazz', 'R&B'],
    google_rating: 4.5,
    google_review_count: 2100,
    has_cover_charge: false,
    cover_notes: null,
    is_active: true,
    is_open_now: true,
    photo_url: null,
    lat: 43.6426,
    lng: -79.4261,
  },
  {
    id: 'mock-3',
    name: 'Lavelle',
    slug: 'lavelle',
    neighbourhood: 'Entertainment District',
    neighbourhood_id: 'mock-ed',
    address: '627 King St W, Toronto',
    venue_type: 'rooftop' as const,
    vibe_tags: ['rooftop', 'first-date', 'chill'],
    music_genres: ['House', 'Afrobeats'],
    google_rating: 4.6,
    google_review_count: 3400,
    has_cover_charge: true,
    cover_notes: 'Reservation recommended',
    is_active: true,
    is_open_now: false,
    photo_url: null,
    lat: 43.6447,
    lng: -79.4002,
  },
  {
    id: 'mock-4',
    name: 'Coda',
    slug: 'coda',
    neighbourhood: 'Entertainment District',
    neighbourhood_id: 'mock-ed',
    address: '794 Bathurst St, Toronto',
    venue_type: 'nightclub' as const,
    vibe_tags: ['dancey', 'late-night', 'live-music'],
    music_genres: ['Techno', 'House'],
    google_rating: 4.2,
    google_review_count: 1560,
    has_cover_charge: true,
    cover_notes: '$20 cover after 11pm',
    is_active: true,
    is_open_now: true,
    photo_url: null,
    lat: 43.6504,
    lng: -79.4126,
  },
]

export const MOCK_DEALS = [
  {
    id: 'deal-1',
    venue_id: 'mock-1',
    venue_name: 'Toybox',
    neighbourhood: 'King West',
    description: 'Free entry before 11pm',
    valid_until: '11:00 PM',
    distance_km: 0.8,
  },
  {
    id: 'deal-2',
    venue_id: 'mock-4',
    venue_name: 'Coda',
    neighbourhood: 'Entertainment District',
    description: 'Ladies free every Friday',
    valid_until: 'Midnight',
    distance_km: 1.2,
  },
  {
    id: 'deal-3',
    venue_id: 'mock-2',
    venue_name: 'The Drake Hotel',
    neighbourhood: 'Ossington',
    description: 'Happy hour until 9pm — 2 for 1 cocktails',
    valid_until: '9:00 PM',
    distance_km: 2.1,
  },
]

export const MOCK_CROWD_SIGNALS: Record<string, number> = {
  'mock-1': 78,
  'mock-2': 42,
  'mock-3': 0,
  'mock-4': 91,
}

export const VIBE_CONFIG: Record<
  string,
  { label: string; emoji: string; desc: string; colors: [string, string] }
> = {
  dancey: {
    label: 'Dancey',
    emoji: '🕺',
    desc: 'High energy, packed dance floors',
    colors: ['#2D0057', '#7B1FA2'],
  },
  chill: {
    label: 'Chill',
    emoji: '🌙',
    desc: 'Low-key bars, good conversation',
    colors: ['#071828', '#0D3A5C'],
  },
  rooftop: {
    label: 'Rooftop',
    emoji: '🏙️',
    desc: 'Sky views over the city',
    colors: ['#051520', '#0A3347'],
  },
  'late-night': {
    label: 'Late Night',
    emoji: '🦉',
    desc: 'Going until 3am or beyond',
    colors: ['#150A2E', '#3D1A6B'],
  },
  'first-date': {
    label: 'First Date',
    emoji: '✨',
    desc: 'Intimate, impressive, memorable',
    colors: ['#2D0A1A', '#7A1A3D'],
  },
  lgbtq: {
    label: 'LGBTQ+',
    emoji: '🏳️‍🌈',
    desc: 'Inclusive, celebratory, safe spaces',
    colors: ['#1A0D2E', '#4B1A6E'],
  },
  'live-music': {
    label: 'Live Music',
    emoji: '🎸',
    desc: 'Bands, DJs, live performances',
    colors: ['#1A0D00', '#5C3300'],
  },
  'bar-crawl': {
    label: 'Bar Crawl',
    emoji: '🍺',
    desc: 'Multiple stops, all night long',
    colors: ['#0A1A08', '#1A4715'],
  },
}

export const BUDGET_TIERS = [
  { max: 20,  label: 'Free night',  sub: 'Cover-free only' },
  { max: 50,  label: 'Casual',      sub: '$20–50' },
  { max: 100, label: 'Moderate',    sub: '$50–100' },
  { max: 150, label: 'Big night',   sub: '$100–150' },
  { max: 201, label: 'Splurge',     sub: '$150+' },
]
